version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_ENV: dev
    container_name: symfony_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www:delegated
    environment:
      APP_ENV: dev
      DATABASE_URL: "mysql://user:password@database:3306/mydb?serverVersion=8.0"
    depends_on:
      - database

  database:
    image: mysql:8.0
    container_name: symfony_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
