version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_ENV: dev
    container_name: symfony_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www:delegated
    environment:
      APP_ENV: dev
      DATABASE_URL: "mysql://user:password@database:3306/mydb?serverVersion=8.0"
    depends_on:
      - database
      - elasticsearch

  database:
    image: mysql:8.0
    container_name: symfony_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTICSEARCH_USERNAME="elastic"
      - ELASTICSEARCH_PASSWORD="XNuiHkJS8no02q+4K2j- "
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:8.5.3
    container_name: logstash
    ports:
      - "5044:5044"
    environment:
      ELASTICSEARCH_USERNAME: "elastic"
      ELASTICSEARCH_PASSWORD: "XNuiHkJS8no02q+4K2j- "
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.3
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
      ELASTICSEARCH_SERVICE_TOKEN: "AAEAAWVsYXN0aWMva2liYW5hL2RlZmF1bHQ6TExWSDZFZzNRTDZ0X19XODVZb01pQQ"
      # ELASTICSEARCH_USERNAME: "elastic"
      # ELASTICSEARCH_PASSWORD: "XNuiHkJS8no02q+4K2j- "

volumes:
  db-data:
  es-data:
